#!/usr/bin/env python3
"""Build docs/limitations/_index.yaml from the .md entries in docs/limitations/.

Each entry is read for its YAML frontmatter (id, title, severity, affects,
since, status). README.md is excluded. The output is a flat YAML list, one
entry per dict, in alphabetical order by id. The agent context block consumes
this file instead of the full .md bodies — keeps the agent's per-call input
token count low.

Run as part of run.sh after dbt admin (so the index reflects whatever was
checked in / hand-edited since the last run). Idempotent. Stdlib-only so it
runs in any python3 (Mac system, EC2 venv, etc.).
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
LIMS_DIR = REPO / "docs" / "limitations"
OUT_PATH = LIMS_DIR / "_index.yaml"
EXCLUDE = {"README.md", "_index.yaml"}


def parse_frontmatter(path: Path) -> dict | None:
    """Tiny stdlib-only YAML frontmatter parser.

    Limitations.md frontmatter is well-shaped: scalar fields and one
    list field (`affects`). This parser handles those; it is not a
    general YAML parser.
    """
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---\n"):
        return None
    end = text.find("\n---\n", 4)
    if end == -1:
        return None
    fm = text[4:end]
    out: dict = {}
    current_list_key: str | None = None
    for line in fm.splitlines():
        if not line.strip():
            continue
        m = re.match(r"^([a-zA-Z_][\w-]*):\s*(.*)$", line)
        if m:
            key, value = m.group(1), m.group(2).strip()
            if value == "":
                out[key] = []
                current_list_key = key
            else:
                out[key] = value
                current_list_key = None
            continue
        m = re.match(r"^\s+-\s+(.+)$", line)
        if m and current_list_key is not None:
            out[current_list_key].append(m.group(1).strip())
            continue
    return out


def yaml_dump_entries(entries: list[dict]) -> str:
    """Emit a flat YAML list of dicts. Hand-rolled to avoid a PyYAML dep
    so this script runs in any python3.
    """
    out: list[str] = []
    for e in entries:
        out.append(f"- id: {e['id']}")
        out.append(f"  title: {_quote(e['title'])}")
        out.append(f"  severity: {e['severity']}")
        out.append("  affects:")
        for a in e["affects"]:
            out.append(f"    - {a}")
        out.append(f"  path: {e['path']}")
    return "\n".join(out) + "\n"


def _quote(s: str) -> str:
    if any(c in s for c in ":#'\"") or s.startswith(("-", "?", ":", "!", "&", "*")):
        escaped = s.replace("\\", "\\\\").replace('"', '\\"')
        return f'"{escaped}"'
    return s


def main() -> int:
    entries: list[dict] = []
    for md in sorted(LIMS_DIR.glob("*.md")):
        if md.name in EXCLUDE:
            continue
        fm = parse_frontmatter(md)
        if fm is None:
            print(f"warning: skipping {md.name} (no frontmatter)", file=sys.stderr)
            continue
        required = {"id", "title", "severity", "affects", "since", "status"}
        missing = required - fm.keys()
        if missing:
            print(f"warning: {md.name} missing fields: {sorted(missing)}", file=sys.stderr)
            continue
        if fm["status"] != "active":
            continue
        entries.append({
            "id": fm["id"],
            "title": fm["title"],
            "severity": fm["severity"],
            "affects": fm["affects"],
            "path": f"docs/limitations/{md.name}",
        })

    OUT_PATH.write_text(
        "# Auto-generated by scripts/build_limitations_index.py — do not hand-edit.\n"
        "# Source: docs/limitations/*.md frontmatter (active entries only).\n"
        + yaml_dump_entries(entries),
        encoding="utf-8",
    )
    print(f"wrote {OUT_PATH.relative_to(REPO)} with {len(entries)} active entries")
    return 0


if __name__ == "__main__":
    sys.exit(main())
